apiVersion: v1
kind: Service
metadata:
  name: devops-app-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: devops-app
  ports:
    - port: 80
      targetPort: 5001
      nodePort: 30007
